# dynamic.yml
# Middleware Configuration
http:
  # Define the backend service that Traefik should use for step-ca
  middlewares:
    ipwhitelist-generic:
      ipWhiteList:
        sourceRange:
          - "10.9.9.0/24" # your WireGuard subnet
          - "127.0.0.1/32" # optional, allow localhost
    secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "no-referrer-when-downgrade"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https: wss:; img-src 'self' data:; font-src 'self' data:;"
    # Adds rate limiting (basic protection against abuse)
    rate-limit:
      rateLimit:
        average: 100 # average requests per second
        burst: 50 # how many requests in a short burst
    # Basic auth middleware for dashboard - replace the hashed password below
    dashboard-auth:
      basicAuth:
        # Format: - "user:hashedpassword"
        users:
          - "admin:$2y$05$PUhVuDG8kpu9UP0ynls/eOoQoYlNsX7XJI3EX/DmrZJOv3qKUjlcC"
