#version: '3.8'
# DB related containers
name: cv-db-stack

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: rootdb
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_DATA_ROOT}/mariadb-data/data:/var/lib/mysql:rw
      - ${DOCKER_DATA_ROOT}/mariadb-data/config/maria.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ${DOCKER_DATA_ROOT}/mariadb-data/backups:/backups:rw
      - ${DOCKER_DATA_ROOT}/mariadb-data/initdb:/docker-entrypoint-initdb.d:ro
      - ${DOCKER_DATA_ROOT}/mariadb-data/log:/var/log/mysql
    networks:
      - cv-db-stack-network
    healthcheck:
      test: ["CMD-SHELL", "[ -S /run/mysqld/mysqld.sock ] || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}" # adjust to your download folder owner
    environment:
      # Adminer connects to DB by host; do NOT expose DB ports publicly
      ADMINER_DESIGN: "nette"
      # If you want to enable plugins, set ADMINER_PLUGINS and mount plugins dir
      DMINER_PLUGINS: "tables-filter,header,capabilities"
    volumes:
      # optionally expose plugins folder:
      - ${DOCKER_DATA_ROOT}/adminer-data/plugins:/var/www/html/plugins-enabled:ro
    networks:
      - cv-db-stack-network
      - cv-base-stack-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_HOST}`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=le"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      #- "traefik.http.routers.adminer.middlewares=ipwhitelist-generic@file,rate-limit@file"
      - "traefik.http.routers.adminer.middlewares=rate-limit@file"
      # Optional: restrict access to a subnet (e.g., your office or wireguard)
      # - "traefik.http.routers.adminer.middlewares=ipwhitelist@file,secure-adminer@file"

networks:
  cv-base-stack-network:
    external: true # Means the dont create new refer existing
  cv-db-stack-network:
    name: cv-db-stack-network
    driver: bridge
