# version: "3.8"
# CV Monitoring containers 
name: cv-mon-stack

# =======================================================================
# 🧭 INDUSTRY-STANDARD MONITORING STACK
# -----------------------------------------------------------------------
# This stack provides full observability for Docker-based workloads:
#   • Prometheus     - collects and stores metrics
#   • Node Exporter  - exposes host-level system metrics
#   • cAdvisor       - collects container-level resource usage
#   • Grafana        - visualizes metrics and logs
#   • Alertmanager   - handles alert notifications
#   • Loki + Promtail - centralized log aggregation
#
# Ideal for: Production, lab, or portfolio demonstration environments
# =======================================================================

services:
  # ---------------------------------------------------------------------
  # 🧱 Prometheus: Core metrics database & scraper
  # ---------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    #ports:
      #- "9090:9090" # Web UI and API
    volumes:
      # Main configuration file (defines scrape targets & rules)
      - ${DOCKER_CONFIG_ROOT}/prometheus-data/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # Persistent data volume to store time-series metrics
      - ${DOCKER_DATA_ROOT}/prometheus-data/data:/prometheus
    command:
      # Retain 15 days of metrics (adjust for your disk size)
      - --storage.tsdb.retention.time=15d
      - --config.file=/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=vault"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      - "traefik.http.routers.prometheus.middlewares=ipwhitelist-generic@file,rate-limit@file"
    networks:
      - cv-mon-stack-network
      - cv-base-stack-network

  # ---------------------------------------------------------------------
  # 📊 Grafana: Dashboard visualization for metrics and logs
  # ---------------------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
    #ports:
      #- "3000:3000" # Web UI (login: admin / admin)
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      # Uncomment below to allow anonymous viewing
      # - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      # Auto-provision Prometheus + Loki as data sources
      - ${DOCKER_CONFIG_ROOT}/grafana-data/provisioning:/etc/grafana/provisioning:ro
      # Store dashboards, data sources, and user sessions
      - ${DOCKER_DATA_ROOT}/grafana-data/data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=vault"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      - "traefik.http.routers.grafana.middlewares=ipwhitelist-generic@file,rate-limit@file"
    networks:
      - cv-mon-stack-network
      - cv-base-stack-network

  # ---------------------------------------------------------------------
  # 🚨 Alertmanager: Handles alerts triggered by Prometheus rules
  # ---------------------------------------------------------------------
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    #ports:
      #- "9093:9093" # Web UI for alerts
    volumes:
      # Configuration defines receivers (email, Slack, webhook, etc.)
      - ${DOCKER_CONFIG_ROOT}/alertmanager-data/config/config.yml:/etc/alertmanager/config.yml:ro
    command:
      - --config.file=/etc/alertmanager/config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`${ALERT_MANAGER_HOST}`)"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.http.routers.alertmanager.entrypoints=websecure"
      - "traefik.http.routers.alertmanager.tls=true"
      - "traefik.http.routers.alertmanager.tls.certresolver=vault"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      - "traefik.http.routers.alertmanager.middlewares=ipwhitelist-generic@file,rate-limit@file"
  networks:
      - cv-mon-stack-network
      - cv-base-stack-network


  # ---------------------------------------------------------------------
  # 📜 Loki: Log aggregation system (like lightweight Elasticsearch)
  # ---------------------------------------------------------------------
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    restart: unless-stopped
    #ports:
      #- "3100:3100" # API and metrics endpoint
    volumes:
      - ${DOCKER_CONFIG_ROOT}/loki-data/config/config.yaml:/etc/loki/local-config.yaml:ro
      - ${DOCKER_DATA_ROOT}/loki-data/data:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`${LOKI_HOST}`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=vault"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      - "traefik.http.routers.loki.middlewares=ipwhitelist-generic@file,rate-limit@file"
    networks:
        - cv-mon-stack-network
        - cv-base-stack-network

# ---------------------------------------------------------------------
  # 🧍 Node Exporter: Exposes host metrics (CPU, memory, disk, network)
  # ---------------------------------------------------------------------
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: "host" # Allows access to host /proc for accurate stats
    network_mode: host
    ports:
      - "9100:9100" # Prometheus scrapes this endpoint
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      # Set root path for mounted host filesystem
      - "--path.rootfs=/rootfs"
      - "--collector.textfile.directory=/textfile_collector"

  # ---------------------------------------------------------------------
  # 📦 cAdvisor: Container-level metrics (CPU, memory, IO, network)
  # ---------------------------------------------------------------------
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080" # Web UI and Prometheus metrics
    volumes:
      # Access Docker and system directories in read-only mode
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - cv-mon-stack-network
      - cv-base-stack-network
  
  # ---------------------------------------------------------------------
  # 🪵 Promtail: Log collector that ships logs from host + containers to Loki
  # ---------------------------------------------------------------------
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      # Read host and container logs
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Promtail config defines log sources and Loki endpoint
      - ${DOCKER_CONFIG_ROOT}/promtail-data/config/config.yml:/etc/promtail/config.yml:ro
    networks:
      - cv-mon-stack-network
      - cv-base-stack-network

networks:
  cv-base-stack-network:
    external: true # Means the dont create new refer existing
  cv-mon-stack-network:
    name: cv-mon-stack-network
    driver: bridge