# version: "3.8"
# CV Monitoring containers 
name: cv-mon-stack

# =======================================================================
# 🧭 INDUSTRY-STANDARD MONITORING STACK
# -----------------------------------------------------------------------
# This stack provides full observability for Docker-based workloads:
#   • Prometheus     - collects and stores metrics
#   • Node Exporter  - exposes host-level system metrics
#   • cAdvisor       - collects container-level resource usage
#   • Grafana        - visualizes metrics and logs
#   • Alertmanager   - handles alert notifications
#   • Loki + Promtail - centralized log aggregation
#
# Ideal for: Production, lab, or portfolio demonstration environments
# =======================================================================

services:
  # ---------------------------------------------------------------------
  # 🧱 Prometheus: Core metrics database & scraper
  # ---------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    #ports:
      #- "9090:9090" # Web UI and API
    volumes:
      # Main configuration file (defines scrape targets & rules)
      - ${DOCKER_CONFIG_ROOT}/prometheus-data/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # Persistent data volume to store time-series metrics
      - ${DOCKER_DATA_ROOT}/prometheus-data/data:/prometheus
    command:
      # Retain 15 days of metrics (adjust for your disk size)
      - --storage.tsdb.retention.time=15d
      - --config.file=/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=vault"
      # Use your Traefik file provider to create 'secure-adminer' that has basicAuth
      - "traefik.http.routers.prometheus.middlewares=ipwhitelist-generic@file,rate-limit@file"
    networks:
      - cv-mon-stack-network
      - cv-base-stack-network

networks:
  cv-base-stack-network:
    external: true # Means the dont create new refer existing
  cv-mon-stack-network:
    name: cv-mon-stack-network
    driver: bridge