#version: '3.8'
name: cv-base-services

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    profiles: [ "infra" ]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - "${DOCKER_DATA_ROOT}/traefik-data/config:/etc/traefik:rw"
      - "${DOCKER_DATA_ROOT}/traefik-data/config/acme.json:/acme.json"
      - "${DOCKER_DATA_ROOT}/traefik-data/log:/var/log/traefik:rw"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ:-UTC}
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - web
    command:
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
    labels:
      - "traefik.enable=true"
      # Dashboard router (routes to Traefik internal api)
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
      # Attach file-provided middlewares (secure headers + basic auth)
      - "traefik.http.routers.traefik.middlewares=dashboard-auth@file,secure-headers@file"
      
networks:
  web:
    driver: bridge
