#version: '3.8'
name: cv-base-services

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    # profiles: ["infra"] # docker compose --profile infra config/up etc
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - "${DOCKER_DATA_ROOT}/traefik-data/config:/etc/traefik:rw"
      - "${DOCKER_DATA_ROOT}/traefik-data/config/acme.json:/acme.json"
      - "${DOCKER_DATA_ROOT}/traefik-data/log:/var/log/traefik:rw"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ:-UTC}
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - web
    command:
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
    labels:
      - "traefik.enable=true"
      # Dashboard router (routes to Traefik internal api)
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
      # Attach file-provided middlewares (secure headers + basic auth)
      - "traefik.http.routers.traefik.middlewares=dashboard-auth@file,secure-headers@file"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # profiles: ["infra"]
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - "${DOCKER_DATA_ROOT}/portainer-data/config:/data:rw"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      # Explicit server port inside the container (Portainer default is 9000)
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Add middlewares (make sure they exist in dynamic.yml)
      - "traefik.http.routers.portainer.middlewares=secure-headers@file,rate-limit@file"
    networks:
      - web
    healthcheck:
      disable: true

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    depends_on:
      - traefik
      - wg-easy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: fog
      MYSQL_USER: fog
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_DATA_ROOT}/mariadb-data/data:/var/lib/mysql:rw
      - ${DOCKER_DATA_ROOT}/mariadb-data/config/maria.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ${DOCKER_DATA_ROOT}/mariadb-data/backups:/backups:rw
      - ${DOCKER_DATA_ROOT}/mariadb-data/initdb:/docker-entrypoint-initdb.d:ro
      - ${DOCKER_DATA_ROOT}/mariadb-data/log:/var/log/mysql
    tmpfs:
      - /var/run
      - /var/lib/mysqltmp
    networks:
      - web
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    # profiles: ["vpn"]
    restart: unless-stopped
    network_mode: host # Required for better networking etc.
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #sysctls: # Enable if bridge network mode used 
      #- net.ipv4.conf.all.src_valid_mark=1
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_ADMIN_PASS}
      - WG_DEFAULT_ADDRESS=10.9.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      # Optional: set WG_PORT if you want a non-default inside container
      # - WG_PORT=51820
    volumes:
      - "${DOCKER_DATA_ROOT}/wgeasy-data/config:/etc/wireguard:rw"
      - "${DOCKER_DATA_ROOT}/wgeasy-data/log:/var/log/wgeasy:rw"
    # expose UDP WireGuard port on host (required)
    #ports: # Enable if bridge network mode used because host mode automatically bind
      #- "51820:51820/udp"
    # do NOT publish 51821: let Traefik serve the UI via HTTPs instead
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgeasy.rule=Host(`${WG_HOST}`)"
      - "traefik.http.routers.wgeasy.entrypoints=websecure"
      - "traefik.http.routers.wgeasy.tls=true"
      - "traefik.http.routers.wgeasy.tls.certresolver=le"
      - "traefik.http.services.wgeasy.loadbalancer.server.port=51821"
      - "traefik.http.routers.wgeasy.middlewares=rate-limit@file"
      #networks:
      #- web
    healthcheck:
      # prefer HTTP healthcheck against the UI if present
      disable: true


networks:
  web:
    driver: bridge
